    
    echo "The different QoS parameters configured for each slice"
    echo ""
    
    echo "┌─────────────────────────────────────────────────────────────────────┐"
    echo "│                    CONFIGURED SLICE PARAMETERS                     │"
    echo "├───────────────────┬────────────────────┬───────────────────────────┤"
    echo "│ Parameter         │ Slice 1 (eMBB)     │ Slice 2 (uRLLC)           │"
    echo "├───────────────────┼────────────────────┼───────────────────────────┤"
    echo "│ S-NSSAI           │ SST=1, SD=1        │ SST=2, SD=1               │"
    echo "│ DNN               │ slice1             │ slice2                    │"
    echo "│ 5QI               │ 9 (best effort)    │ 1 (priority)              │"
    echo "│ Session AMBR DL   │ 100 Mbps           │ 40 Mbps                   │"
    echo "│ Session AMBR UL   │ 50 Mbps            │ 20 Mbps                   │"
    echo "│ IP Pool           │ 12.1.1.0/24        │ 12.2.1.0/24               │"
    echo "│ SMF               │ oai-smf-slice1     │ oai-smf-slice2            │"
    echo "│ UPF               │ oai-upf-slice1     │ oai-upf-slice2            │"
    echo "└───────────────────┴────────────────────┴───────────────────────────┘"
    echo ""
    echo ""